### ISSUE TITLE
Why network access?

### ISSUE THREAD

**Issue by zefr0x** [flathub/io.github.sigmasd.nosleep#5] opened 2023-12-12 13:07 UTC
https://github.com/flathub/io.github.sigmasd.nosleep/blob/94577f345929cc7d37cc37c010f825b753f5b915/io.github.sigmasd.nosleep.yml#L23-L24

I don't see any point of having network access. This application should never have network access, since nothing of its functionalities require it.

I don't know how deno works exactly, but you should just include these dependencies inside the package.

With a quick search I found this: https://docs.deno.com/runtime/manual/tools/vendor

**Comment by sigmaSd** [comment] 2023-12-12 17:36
Yes its unfortunate but should be fixable.

The problem is flatpak forbid network access so I can't use `deno vendor` at build time.

The correct way to fix is this is to have the sources pre-generated like for example cargo have this https://github.com/flatpak/flatpak-builder-tools/blob/master/cargo/flatpak-cargo-generator.py and each language/runtime have this.
But this would be a good amount of work to figure this.

I guess the easy way for now is to  check the vendor-ed code in the repo.

**Comment by sigmaSd** [comment] 2023-12-12 20:42
Fixed in 0.3.6, flathub should take sometime to upload the new version

**Closed as completed** 2023-12-12 20:42 UTC
